import { createContext, useContext, useState, ReactNode } from "react";

type Language = "te" | "en" | "hi";

interface LanguageContextType {
  language: Language | null;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  te: {
    appName: "స్మృతి సేతు",
    appSubtitle: "స్మృతి సేతు — Bridge of Remembrance",
    appDesc: "ప్రేమ మరియు భక్తితో మీ పూర్వీకులను గౌరవించండి.",
    openDashboard: "డాష్‌బోర్డ్ తెరవండి",
    beginJourney: "మీ యాత్ర ప్రారంభించండి",
    signIn: "లాగిన్ అవుదాం",
    todayPanchangam: "నేటి పంచాంగం",
    sacredFeatures: "మీ కుటుంబానికి పవిత్ర సౌలభ్యాలు",
    honoringAncestors: "తరాలు దాటి పూర్వీకులను గౌరవిస్తున్నాం",
    feat1Title: "పంచాంగం క్యాలెండర్",
    feat1Desc: "తిధి, నక్షత్రం & మాసం ట్రాక్ చేయండి.",
    feat2Title: "స్మార్ట్ రిమైండర్లు",
    feat2Desc: "ప్రతి వార్షికానికి 1 నెల, 15 రోజులు, 7 రోజులు, 1 రోజు ముందు నోటిఫికేషన్ పొందండి.",
    feat3Title: "వంశ వృక్షం",
    feat3Desc: "అందమైన కుటుంబ కార్డులతో పూర్వీకులను పొందుపరచండి.",
    feat4Title: "AI స్మృతి",
    feat4Desc: "AI ద్వారా స్మృతి సందేశాలు మరియు విధి సూచనలు.",
    feat5Title: "జ్ఞాపకాల గ్యాలరీ",
    feat5Desc: "ఇష్టమైన జ్ఞాపకాలు, సంప్రదాయాలు శాశ్వతంగా నిలపండి.",
    feat6Title: "ఆధ్యాత్మిక వచనాలు",
    feat6Desc: "భగవద్గీత, ఉపనిషత్తులు నుండి రోజువారీ వచనాలు.",
    dashboard: "డాష్‌బోర్డ్",
    ancestors: "పూర్వీకులు",
    reminders: "రిమైండర్లు",
    settings: "సెట్టింగ్లు",
    logout: "లాగ్అవుట్",
    save: "సేవ్ చేయి",
    cancel: "రద్దు",
    add: "జోడించు",
    edit: "సవరించు",
    delete: "తొలగించు",
    search: "వెతుకు",
    loading: "లోడ్ అవుతోంది...",
    welcome: "స్వాగతం",
    changeLanguage: "భాష మార్చు",
    panchangam: "పంచాంగం",
    notifications: "నోటిఫికేషన్లు",
    familyTree: "వంశ వృక్షం",
    memoryGallery: "జ్ఞాపకాల గ్యాలరీ",
    dashboardSubtitle: "మీ పూర్వీకుల ఆశీర్వచనాలు మిమ్మల్ని నడిపించుగాక.",
    todayRemembrances: "నేటి స్మరణలు",
    upcomingRemembrances: "రాబోయే స్మరణలు",
    noUpcoming: "వచ్ఛే 90 రోజుల్లో ఎటువంటి స్మరణలు లేవు.",
    addAncestor: "పూర్వీకులను జోడించు",
    recordMemory: "వారి జ్ఞాపకాన్ని నిలిపించు",
    fullCalendar: "సంపూర్ణ క్యాలెండర్",
    dailyQuote: "నేటి వచనం",
    thisMonth: "ఈ నెల",
    thisWeek: "ఈ వారం",
    today: "నేడు",
    viewAll: "అన్నీ చూడు",
    viewAllAncestors: "అన్ని పూర్వీకులను చూడండి",
    searchAncestors: "పూర్వీకులను వెతుకు...",
    noAncestors: "ఇంకా పూర్వీకులు లేరు",
    panchangamCalendar: "పంచాంగం క్యాలెండర్",
    tithi: "తిధి",
    nakshatram: "నక్షత్రం",
    masam: "మాసం",
    paksham: "పక్షం",
    vara: "వారం",
    auspiciousTimes: "శుభ సమయాలు",
    inauspiciousTimes: "అశుభ సమయాలు",
    allRead: "అన్ని చదివారు",
    allCaughtUp: "అన్నీ చూశారు",
    unread: "చదవలేదు",
    father: "తండ్రి",
    grandfather: "తాతయ్య",
    greatGrandfather: "ముత్తాతయ్య",
    paternalUncle: "పెద్దన్న",
    paternalAunt: "పెద్దమ్మ",
    mother: "తల్లి",
    grandmother: "నాన్మమ్మ",
    greatGrandmother: "ముత్తామ్మ",
    maternalUncle: "మేనమామ",
    maternalAunt: "పిన్నమ్మ",
    vardhanti: "వార్ధంతి",
    birthdayRemembrance: "పుట్టినరోజు స్మరణ",
    generalRemembrance: "సామాన్య స్మరణ",
    chooseAncestor: "పూర్వీకులను ఎంచుకోండి...",
    newQuote: "కొత్త వచనం",
    wisdomCollection: "జ్ఞాన సంకలనం",
    basicDetails: "మూల వివరాలు",
    familyDetails: "కుటుంబ వివరాలు",
    remembranceSettings: "స్మరణ సెట్టింగ్స్",
    fullName: "పూర్తి పేరు",
    relationship: "సంబంధం",
    gender: "లింగం",
    dateOfDeath: "మరణ తేది (వార్ధంతి)",
    dateOfBirth: "పుట్టిన తేది",
    place: "స్థళం",
    photo: "ఫోట౏",
    changePhoto: "ఫోట౏ మార్చు",
    uploadPhoto: "ఫోట౏ అప్లోడ్ చేయి",
    spiritualDetails: "ఆధ్యాత్మిక / పంచాంగం వివరాలు",
    samvatsaram: "సంవత్సరం",
    teluguYearName: "తెలుగు సంవత్సర పేరు",
    timeOfDeath: "మరణ సమయం",
    familySide: "కుటుంబ వైపు",
    gotram: "గోత్రం",
    remindMe: "నన్ను గుర్తు చేయి",
    ritualNotes: "విధి వివరాలు",
    importantTraditions: "ముఖ్యమైన సంప్రదాయాలు",
    favoriteMemories: "ఇష్టమైన జ్ఞాపకాలు",
    prasadam: "నైవేద్యం / ప్రసాదం",
    additionalNotes: "అదనపు వివరాలు...",
    additionalTraditions: "అదనపు సంప్రదాయాలు...",
    additionalMemories: "అదనపు జ్ఞాపకాలు...",
    additionalPrasadam: "అదనపు ప్రసాదం వివరాలు...",
    select: "ఎంచుకోండి",
    selectSide: "వైపు ఎంచుకోండి",
    maternal: "తాయి వైపు",
    paternal: "తండ్రి వైపు",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతరం",
    "1monthBefore": "1 నెల ముందు",
    "15daysBefore": "15 రోజులు ముందు",
    "7daysBefore": "7 రోజులు ముందు",
    "1dayBefore": "1 రోజు ముందు",
    ancestorAdded: "పూర్వీకుపుడు జోడించబడ్డారు",
    familyTreeDesc: "మీ వంశ చెట్టు, కుటుంబ శాఖ వారీగా.",
    otherBranch: "ఇతర శాఖ",
    paternalBranch: "తండ్రి వైపు శాఖ",
    maternalBranch: "తాయి వైపు శాఖ",
    smartReminders: "స్మార్ట్ రిమైండర్లు",
    remindersDesc: "మీ పూర్వీకుల స్మరణ తేదిలతో అనుసంధానంలో ఉండండి.",
    upcomingNext90: "రాబోయే 90 రోజులు",
    noRemindersToday: "నేడు ఏ రిమైండర్లు లేవు. శాంతిగా ఉంది.",
    reminderSchedule: "రిమైండర్ షెడ్యూల్",
    autoNotifyDesc: "ప్రతి వార్ధంతికి ముందు స్మృతిసేతు నోటిఫై చేస్తుంది:",
    generateMessage: "సందేశం రూపొందించు",
    selectAncestor: "పూర్వీకులను ఎంచుకోండి",
    occasion: "సందర్భం",
    remembranceMessage: "స్మరణ సందేశం",
    aiRemembranceDesc: "హృద్యంగా ఆధ్యాత్మిక సందేశాలు రూపొందించండి.",
  },
  en: {
    appName: "SmritiSetu",
    appSubtitle: "స్మృతి సేతు — Bridge of Remembrance",
    appDesc: "Honor your ancestors with love and devotion. Track Vardhanti, Tithi, and Nakshatram remembrance dates.",
    openDashboard: "Open Dashboard",
    beginJourney: "Begin Your Journey",
    signIn: "Sign In",
    todayPanchangam: "Today's Panchangam",
    sacredFeatures: "Sacred Features for Your Family",
    honoringAncestors: "Honoring ancestors across generations",
    feat1Title: "Panchangam Calendar",
    feat1Desc: "Track Tithi, Nakshatram & Masam with authentic Telugu Panchangam integration.",
    feat2Title: "Smart Reminders",
    feat2Desc: "Get notified 1 month, 15 days, 7 days, and 1 day before each anniversary.",
    feat3Title: "Family Tree",
    feat3Desc: "Organize maternal and paternal ancestors with beautiful family cards.",
    feat4Title: "AI Remembrance",
    feat4Desc: "AI-generated spiritual messages, ritual suggestions & remembrance quotes.",
    feat5Title: "Memory Gallery",
    feat5Desc: "Preserve favorite memories, traditions, and prasadam details forever.",
    feat6Title: "Spiritual Quotes",
    feat6Desc: "Daily quotes from Bhagavad Gita, Upanishads & Telugu wisdom traditions.",
    dashboard: "Dashboard",
    ancestors: "Ancestors",
    reminders: "Reminders",
    settings: "Settings",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    search: "Search",
    loading: "Loading...",
    welcome: "Welcome",
    changeLanguage: "Change Language",
    panchangam: "Panchangam",
    notifications: "Notifications",
    familyTree: "Family Tree",
    memoryGallery: "Memory Gallery",
    dashboardSubtitle: "May your ancestors' blessings guide your day.",
    todayRemembrances: "Today's Remembrances",
    upcomingRemembrances: "Upcoming Remembrances",
    noUpcoming: "No upcoming remembrances in the next 90 days.",
    addAncestor: "Add Ancestor",
    recordMemory: "Record their memory",
    fullCalendar: "Full Calendar",
    dailyQuote: "Daily Quote",
    thisMonth: "This Month",
    thisWeek: "This Week",
    today: "Today",
    viewAll: "View all",
    viewAllAncestors: "View All Ancestors",
    searchAncestors: "Search ancestors...",
    noAncestors: "No ancestors yet",
    panchangamCalendar: "Panchangam Calendar",
    tithi: "Tithi",
    nakshatram: "Nakshatram",
    masam: "Masam",
    paksham: "Paksham",
    vara: "Vara",
    auspiciousTimes: "Auspicious Times",
    inauspiciousTimes: "Inauspicious Times (Avoid)",
    allRead: "All notifications marked as read",
    allCaughtUp: "All caught up",
    unread: "unread",
    father: "Father",
    grandfather: "Grandfather",
    greatGrandfather: "Great Grandfather",
    paternalUncle: "Paternal Uncle",
    paternalAunt: "Paternal Aunt",
    mother: "Mother",
    grandmother: "Grandmother",
    greatGrandmother: "Great Grandmother",
    maternalUncle: "Maternal Uncle",
    maternalAunt: "Maternal Aunt",
    vardhanti: "Death Anniversary (Vardhanti)",
    birthdayRemembrance: "Birthday Remembrance",
    generalRemembrance: "General Remembrance",
    chooseAncestor: "Choose an ancestor...",
    newQuote: "New Quote",
    wisdomCollection: "Wisdom Collection",
    basicDetails: "Basic Details",
    familyDetails: "Family Details",
    remembranceSettings: "Remembrance Settings",
    fullName: "Full Name",
    relationship: "Relationship",
    gender: "Gender",
    dateOfDeath: "Date of Death (Vardhanti)",
    dateOfBirth: "Date of Birth (optional)",
    place: "Place",
    photo: "Photo",
    changePhoto: "Change Photo",
    uploadPhoto: "Upload Photo",
    spiritualDetails: "Spiritual / Panchangam Details",
    samvatsaram: "Samvatsaram",
    teluguYearName: "Telugu Year Name",
    timeOfDeath: "Time of Death (optional)",
    familySide: "Family Side",
    gotram: "Gotram (optional)",
    remindMe: "Remind me",
    ritualNotes: "Ritual Notes",
    importantTraditions: "Important Traditions",
    favoriteMemories: "Favorite Memories",
    prasadam: "Food Offerings / Prasadam",
    additionalNotes: "Additional notes...",
    additionalTraditions: "Additional traditions...",
    additionalMemories: "Additional memories...",
    additionalPrasadam: "Additional prasadam details...",
    select: "Select",
    selectSide: "Select side",
    maternal: "Maternal",
    paternal: "Paternal",
    male: "Male",
    female: "Female",
    other: "Other",
    "1monthBefore": "1 month before",
    "15daysBefore": "15 days before",
    "7daysBefore": "7 days before",
    "1dayBefore": "1 day before",
    ancestorAdded: "Ancestor added",
    familyTreeDesc: "Your ancestral lineage, organized by family branch.",
    otherBranch: "Other Branch",
    paternalBranch: "Paternal Branch",
    maternalBranch: "Maternal Branch",
    smartReminders: "Smart Reminders",
    remindersDesc: "Stay connected with your ancestors' remembrance dates.",
    upcomingNext90: "Upcoming (Next 90 Days)",
    noRemindersToday: "No reminders for today. All is peaceful.",
    reminderSchedule: "Reminder Schedule",
    autoNotifyDesc: "SmritiSetu automatically notifies you before each ancestor's death anniversary:",
    generateMessage: "Generate Message",
    selectAncestor: "Select Ancestor",
    occasion: "Occasion",
    remembranceMessage: "Remembrance Message",
    aiRemembranceDesc: "Generate heartfelt spiritual messages and remembrance quotes.",
  },
  hi: {
    appName: "स्मृति सेतु",
    appSubtitle: "स्मृति सेतु — यादों का सेतु",
    appDesc: "प्रेम और श्रद्धा से अपने पूर्वजों को सम्मान दें.",
    openDashboard: "डैशबोर्ड खोलें",
    beginJourney: "अपनी यात्रा शुरू करें",
    signIn: "साइन इन",
    todayPanchangam: "आज का पंचांग",
    sacredFeatures: "आपके परिवार के लिए पवित्र सुविधाएं",
    honoringAncestors: "पीढ़ियों से पूर्वजों का सम्मान",
    feat1Title: "पंचांग कैलेंडर",
    feat1Desc: "तिथि, नक्षत्र & मास को ट्रैक करें.",
    feat2Title: "स्मार्ट रिमाइंडर",
    feat2Desc: "प्रत्येक वर्षगांठ से 1 महीने, 15 दिन, 7 दिन, 1 दिन पहले सूचना पाएं.",
    feat3Title: "परिवार वृक्ष",
    feat3Desc: "सुंदर परिवार कार्ड्स के साथ पूर्वजों को संगठित करें.",
    feat4Title: "AI स्मृति",
    feat4Desc: "AI द्वारा आध्यात्मिक संदेश और स्मृति उद्धरण.",
    feat5Title: "स्मृति गैलरी",
    feat5Desc: "प्रिय यादें, परंपराएं हमेशा के लिए संरक्षित करें.",
    feat6Title: "आध्यात्मिक विचार",
    feat6Desc: "भगवद्गीता, उपनिषद से दैनिक विचार.",
    dashboard: "डैशबोर्ड",
    ancestors: "पूर्वज",
    reminders: "रिमाइंडर",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    save: "सहेजें",
    cancel: "रद्द करें",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    search: "खोजें",
    loading: "लोड हो रहा है...",
    welcome: "स्वागत है",
    changeLanguage: "भाषा बदलें",
    panchangam: "पंचांग",
    notifications: "सूचनाएं",
    familyTree: "परिवार वृक्ष",
    memoryGallery: "स्मृति गैलरी",
    dashboardSubtitle: "आपके पूर्वजों का आशीर्वाद आपका दिन संवारे.",
    todayRemembrances: "आज की स्मृतियां",
    upcomingRemembrances: "आने वाली स्मृतियां",
    noUpcoming: "अगले 90 दिनों में कोई स्मृति नहीं.",
    addAncestor: "पूर्वज जोड़ें",
    recordMemory: "उनकी याद दर्ज करें",
    fullCalendar: "पूरा कैलेंडर",
    dailyQuote: "दैनिक विचार",
    thisMonth: "इस महीने",
    thisWeek: "इस सप्ताह",
    today: "आज",
    viewAll: "सभी देखें",
    viewAllAncestors: "सभी पूर्वज देखें",
    searchAncestors: "पूर्वज खोजें...",
    noAncestors: "अभी कोई पूर्वज नहीं",
    panchangamCalendar: "पंचांग कैलेंडर",
    tithi: "तिथि",
    nakshatram: "नक्षत्र",
    masam: "मास",
    paksham: "पक्ष",
    vara: "वार",
    auspiciousTimes: "शुभ समय",
    inauspiciousTimes: "अशुभ समय",
    allRead: "सभी सूचनाएं पढ़ीं",
    allCaughtUp: "सभी देख लिया",
    unread: "अपठित",
    father: "पिता",
    grandfather: "दादा",
    greatGrandfather: "परदादा",
    paternalUncle: "ताउ",
    paternalAunt: "बूआ",
    mother: "माता",
    grandmother: "दादी",
    greatGrandmother: "परदादी",
    maternalUncle: "मामा",
    maternalAunt: "मौसी",
    vardhanti: "वार्षिक तिथि",
    birthdayRemembrance: "जन्मदिन स्मृति",
    generalRemembrance: "सामान्य स्मृति",
    chooseAncestor: "पूर्वज चुनें...",
    newQuote: "नया विचार",
    wisdomCollection: "क्षान संग्रह",
    basicDetails: "मूल विवरण",
    familyDetails: "परिवार विवरण",
    remembranceSettings: "स्मृति सेटिंग्स",
    fullName: "पूरा नाम",
    relationship: "संबंध",
    gender: "लिंग",
    dateOfDeath: "मृत्यु तिथि (वार्धंति)",
    dateOfBirth: "जन्म तिथि",
    place: "स्थान",
    photo: "फोटो",
    changePhoto: "फोटो बदलें",
    uploadPhoto: "फोटो अपलोड करें",
    spiritualDetails: "आध्यात्मिक / पंचांग विवरण",
    samvatsaram: "संवत्सर",
    teluguYearName: "तेलुगु वर्ष नाम",
    timeOfDeath: "मृत्यु समय",
    familySide: "परिवार पक्ष",
    gotram: "गोत्रम",
    remindMe: "मुझे याद दिलाएं",
    ritualNotes: "अनुष्ठान विवरण",
    importantTraditions: "महत्वपूर्ण परंपराएं",
    favoriteMemories: "प्रिय यादें",
    prasadam: "भोजन अर्पण / प्रसाद",
    additionalNotes: "अतिरिक्त विवरण...",
    additionalTraditions: "अतिरिक्त परंपराएं...",
    additionalMemories: "अतिरिक्त यादें...",
    additionalPrasadam: "अतिरिक्त प्रसाद विवरण...",
    select: "चुनें",
    selectSide: "पक्ष चुनें",
    maternal: "मातृ पक्ष",
    paternal: "पितृ पक्ष",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    "1monthBefore": "1 महीने पहले",
    "15daysBefore": "15 दिन पहले",
    "7daysBefore": "7 दिन पहले",
    "1dayBefore": "1 दिन पहले",
    ancestorAdded: "पूर्वज जोड़ा गया",
    familyTreeDesc: "आपका वंशावलि, परिवार शाखा अनुसार व्यवस्थित.",
    otherBranch: "अन्य शाखा",
    paternalBranch: "पितृ पक्ष शाखा",
    maternalBranch: "मातृ पक्ष शाखा",
    smartReminders: "स्मार्ट रिमाइंडर",
    remindersDesc: "अपने पूर्वजों की स्मृति तिथियों से जुड़े रहें.",
    upcomingNext90: "आगामी (90 दिन)",
    noRemindersToday: "आज कोई रिमाइंडर नहीं. शांति है.",
    reminderSchedule: "रिमाइंडर शेड्यूल",
    autoNotifyDesc: "स्मृतिसेतु प्रत्येक वार्षिक तिथि से पहले सूचित करता है:",
    generateMessage: "संदेश उत्पन्न करें",
    selectAncestor: "पूर्वज चुनें",
    occasion: "अवसर",
    remembranceMessage: "स्मृति संदेश",
    aiRemembranceDesc: "हृदयस्पर्शी आध्यात्मिक संदेश और स्मृति उद्धरण उत्पन्न करें.",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language | null>(null);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    if (!language) return key;
    return translations[language]?.[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
